apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-jks
  namespace: dev
spec:
  encryptedData:
    keystore.jks: AgCQcHSjdLx5CkHWbK7/eFJpMQs+G94D3nmgGeuQsaklQfpE06vxlOEBUdmDOE3Ox/myfJ7ZIwA8lxosNcpH7fh/fNw5+YjmmRlEqkeDaA8KMSFhSveNuY8p5d1XTWNZEQpkaI+SNNOrkPrGQ9/dWD1z3DMfBWiVh+r+F6+k/dt+OXWOddEzY4aAJAfW3e92d38TIr1IEfH6fN98CnofS7qtjXphzTZX4fEyh29SyELgyf7k4MiSNYqkdxxCJHNN2MNH3HB0guZ/cRfkQvPj5LASElxntUZ7RzmKwSWDzKb8MTltMWbaztL8syNtDY1LTcMIymt9QG2T9Dp0NSpk4Qq9siAQqfJ/GBKfU/vo9Icev/nEZiPCcT15anbQth3uXHSq86O/2A9AujQPliNFn3r/0IjgePJcM+U2fczJhWvndoXGW6cK6RxKlNEoZZcjqEErmbTsB3Uow83TlKZtK9ffFJp5ZHlPJgP6p0uvV0Cb6CydrCqxy0pHy6pCHTOwZclEFSvsNcRQeExFgVYa2i4TrnXVzOTVc+/PdqQJ5YgPkZbu4uG7D8BYabUmGW4BFp47D38mFTC0vvf75G8A6dCiRYHibd5RWpO24OajchaI1s9IEPxexpcqXi91WLgxzo1KF9IbWyhVk3tqJ1ylFcCZIXyhdUu41uWIg1tEaOkazj7Id4hPW2Es4rTh8jJa0ztiQr4RbwDPeobJKkVW2HGPHHxwHoYB2+gsI2n1YUc5/LHhppBxID1dAa/rKkATbTZgafwIO3QmigWuw7XVj8XSCs6edblINNhqCzNdkGsVyvl+1aoiOB+VK57IFAaeqhgqwf0NhXsPUK3AS/ROnigqskl3Fz5i1jOlUtEDZaiHgQNVgtGwmfe8HMYteCZlcTkR4md7jqmoNuZMxidVJ15HtW5q97ZdtQ1P29RnxzGbtflfXa76FkaPJQaeCV6Du8eghsrCkC+6z0o7vNGSwMeY5yrXUhFJQyoHD2jZPHlv2sHtzCzXBjgDiyvPjFtuYh1j7QaUzhQW1RhBFFcbZFAiHmoZHHbKHECeIOYTLgeO0bw7bsPvCmKAjK7o1KGstLyRDLNMBoCnGXOgnaJSLsuWfbatUOH7v2lVdkwsUjwqBOu7NgLTvDMw7wKnTdddMdzkTviAVAFI1WcbI5Is/bcrzrwB+2Y9QNB1Zzji+C0J0KK6clJBqqLkAZskrk1xD+9FNkwB2yK0g9c9HvX3u9h88eVnxlQrQqHQzRKJMuTuF1xi0fTJM7ZYx3p8Kkj+ScSPyqemiYmGftxZt9BttqSoF40tShlEIZcJckbUxDSSpbNM7I+DgLyZSHRCD0Lh+ZkYWd+txdjFwqOMqfcyoSKjgE9wBl/rhHkX5Lc7oj3w6kJo2GUGjXxS9/pU9WWUB1Yryfunr5QW1QG9By88ApDBVaDFNQnAOE+7L6axvAFLaZMB3pSgYbFTNU/eiWg8WEeLTtKuqY14/JvZnu/Hi23PBnA4n7P+w55QS6UKKjZr9j4YS9YdOquIrAAcEb0ify5wLNXJI0LZ3CvXEPuit2G4RPzasiGl635rmEBARNyvwfhoxM0sIlh9p0LH/tI2y+nXzjLNxL6wWYZlUp0kZXqvYo1runjGPdTSc/xUmXtAziS5ehdWUN/iyeTQvnSzXW3VRA/bAvdqFpOqZc8jJxoMGIDYPyDkV3IH+srEBFMrwIkwFg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-jks
      namespace: dev

