apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-stage-prod-promotion-pipeline-for-qmgr
  namespace: ci
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      serviceAccountName: pipeline
      containers:
      - name: tests-in-dev-env
        image: quay.io/rhcanada/tkn-cli
        command:
          - tkn
        args:
          - -n
          - ci
          - pipeline
          - start
          - ibm-mq-promote-stage-prod
          - --param
          - git-url=https://github.com/tutorials-org-1/mq-qm01.git
          - --param
          - git-revision=qm1-tutorials-org-1
          - --param
          - src-environment=staging
          - --param
          - dest-environment=prod
          - --param
          - app-path="mq/environments"
          - --param
          - qm-security=false
          - --param
          - git-pr=true
          - --param
          - test-plan="jmeter/mq-spring-app.jmx"
      restartPolicy: Never
  backoffLimit: 0
