apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: cnkt-trigger-binding
    interceptors:
      - params:
          - name: filter
            value: >-
              header.match('X-GitHub-Event', 'push') && body.ref ==
              'refs/heads/qm1-tutorials-org-1' && body.repository.full_name ==
              'tutorials-org-1/mq-qm01'
          - name: overlays
            value: null
        ref:
          kind: ClusterInterceptor
          name: cel
    name: mq-qm01-dev
    template:
      ref: mq-qm-dev
  - bindings:
    - kind: TriggerBinding
      ref: cnkt-trigger-binding
    interceptors:
      - params:
          - name: filter
            value: >-
              header.match('X-GitHub-Event', 'push') && body.ref ==
              'refs/heads/mq-spring-tutorials-org-1' &&
              body.repository.full_name == 'tutorials-org-1/mq-spring-app'
          - name: overlays
            value: null
        ref:
          kind: ClusterInterceptor
          name: cel
    name: mq-spring-app-dev
    template:
      ref: mq-spring-app-dev
  - bindings:
    - kind: TriggerBinding
      ref: cnkt-trigger-binding
    interceptors:
      - params:
          - name: filter
            value: >-
              header.match('X-GitHub-Event', 'push') && body.ref ==
              'refs/heads/mq-quarkus-tutorials-org-1' &&
              body.repository.full_name == 'tutorials-org-1/mq-quarkus-app'
          - name: overlays
            value: null
        ref:
          kind: ClusterInterceptor
          name: cel
    name: mq-quarkus-app-dev
    template:
      ref: mq-quarkus-app-dev
