apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mq-quarkus-app-post-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-quarkus-app-post-dev
      template:
        ref: mq-quarkus-app-post-dev