apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  labels:
    app: mq-quarkus-app-post-dev
  name: mq-quarkus-app-post-dev
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Prune=false
        labels:
          tekton.dev/pipeline: ibm-mq-promote-dev-stage
        generateName: ibm-mq-promote-dev-stage-
      spec:
        params:
        - name: git-url
          value: https://github.com/tutorials-org-1/mq-quarkus-app.git
        pipelineRef:
          name: ibm-mq-promote-dev-stage
