apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAh8TUIN8l1NRNthmxCejx3vQMoDXurTDf/CXMuDsrjCuw/KK6KOHi4k2hC4ig8w+Llc31n3XstMv+WLkI5AGtOJ6Z8wZzXYOudFdqUl9HSgb8UFA0/9GqF1UX11pAj4AOesmDaAM584nQYe0OMj8r+46WhW9YEWs3AH9mlZs42WE9cXqNcVVkrQJBTufW1lUYsSmhVpRwBr8wKSOzeivF1GDH0WBayZ0nxeGbo6HNT71cTwpmelpJpzrnfo+BNE0U13KECHjj+SOD7k7QvGUm/KjzrCMknMwkAFR37FvmIxoJThZPPi0hcL/uMIHaHHOjb3+xLddKG7UNs+yYeBaXO4B3NbWrEiBXEaG+rKYwwtLCBCJ8aOEUgLxjOcNwbACyGKuwLO4aWFfo1K1D+b2bGcnNQBdzyXKoQBWtHr2byQXDhbI7Q9A5zDVYRVWUJB66hx9vntf9EGxIXlwKpp8mOlAVjK61NkyLetg+o5/DPg1ji8tCoq6Z2OEYs7L/phfPGvbRMo682fs3T2/jpvXdI2XK2Um0AigXD2fgCVZmM9+HU7cM+kMi7Nz6C6yepg9/7AQJEVv4jHrPtI4ra0JgcTp9aWQKaJUOZmBsSk8mvvgT3cjSRX/8XokzZoVVOK63XYxJZVMTc5OuGNT4aMysDRQFhobpvZ8s75uZ7BvNqlAyQm55wgSienkCEByaqAF2EJACtpKuYMeId7q/Ddtd7FzA7f7xFWeca9W78L1YjZGoLa5Gk9JmXhO9qm851h+8PWg0g19R9hVwqyUeV2O4Jo87IWUYHe6OZN4sdAOiMB1EmSIC45GENmJ4pkgeOa1JAw62Ut46xp8H242rtXTJdGmfnmnanh6FDQz2PBWc2UnaeGbRZg1VxIXuOQQkTc/cGNWYrKrkpd2+2hNz83ujq4oTxR74UCRb6jV74b38JxA==
    IBM_ENTITLED_REGISTRY_USER: AgBalMN9BrrBF78Kby9ODjeiQLuKA1DifNSDaKaqpYXdcfr/DPnLl05d3spkbCst+wfWG1MzUsmPx7R+ldkXm78m70XntpVNr2LFfwVgNI9xMsWJ+H7nc7luI30ETxvZdENc+USCaXb8Fu542R0mo95OLCyjgzb01M4KX2Oi+VPkz+nTiJNfTC14BTK9QrfMjPriElnFW8aygVzlSdPBmV5dysjJJ+bhSqNWMkRjGNwhKXCHuBRJw6uvTOdrqk0xA0b9/5Gl8S8POsyyKZAm479dTsNNqeTYfihfnxK90E2BGCqpHwKFL3DLF7p+fbvW2mLE2yQGuNA9AVxbnhck9KcYQ58mfEVPCDYo88VW9cCrJBzrB72geVJqXvNtGmyeL9cYhqOlHzXnz9UGv3L/Xox/D8A6P+zXNPR8mAwyJ0uSUsyoTWJbbC4j1T/nL6Lu1OOYbZP5O/1XDudLaBnMGKEa710E2h9ihCCChztxfs9i+N2Zv4us9/TRncZYU55PjwBAAmFHmq4QgMTqZ+35dnN/DM+LVpo+q+V9PkUA1kw5AsR1P9Miyikiajlj+NUy+OSCPdEzxkZQBdLG6w5zONXDnJES5SEDC/2fshWBNjWCm2VJaOXTiyp1qKvgW5hpU1KAPYxq61JQOgiYoB80A7WAILxW98SVxsFE+xzdF/sMUjhAO9SS2id9sTR99Pr/n0uaLA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

